# Configuration Docker Compose pour le développement
# Version simplifiée avec hot-reload et ports exposés

version: '3.8'

services:
  # Frontend Nuxt.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: logon-frontend-dev
    ports:
      - "3000:3000"
      - "24678:24678" # HMR port
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE=http://localhost:3001/api
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    networks:
      - logon-dev
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
      - /app/.nuxt
    command: npm run dev

  # Backend Node.js/Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: logon-backend-dev
    ports:
      - "3001:3001"
      - "9229:9229" # Debug port
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://logon:${POSTGRES_PASSWORD}@db:5432/logon
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - logon-dev
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
      - ./logs:/app/logs
    command: npm run dev

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: logon-db-dev
    environment:
      - POSTGRES_DB=logon
      - POSTGRES_USER=logon
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - logon-dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  # Redis Cache & Sessions
  redis:
    image: redis:7-alpine
    container_name: logon-redis-dev
    networks:
      - logon-dev
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

networks:
  logon-dev:
    driver: bridge
    name: logon-development

volumes:
  postgres_dev_data:
    name: logon-postgres-dev
  redis_dev_data:
    name: logon-redis-dev
